/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessType = IDL.Variant({
  'hotel' : IDL.Null,
  'other' : IDL.Text,
  'temple' : IDL.Null,
  'restaurant' : IDL.Null,
  'corporate' : IDL.Null,
});
export const Time = IDL.Int;
export const LeadRequest = IDL.Record({
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'businessType' : BusinessType,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
  'budgetRange' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(LeadRequest)], ['query']),
  'submitEnquiry' : IDL.Func([LeadRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessType = IDL.Variant({
    'hotel' : IDL.Null,
    'other' : IDL.Text,
    'temple' : IDL.Null,
    'restaurant' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const Time = IDL.Int;
  const LeadRequest = IDL.Record({
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'businessType' : BusinessType,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
    'budgetRange' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(LeadRequest)], ['query']),
    'submitEnquiry' : IDL.Func([LeadRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };