/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeadRequest {
    city: string;
    businessName: string;
    businessType: BusinessType;
    email?: string;
    message: string;
    timestamp: Time;
    phone?: string;
    budgetRange: string;
}
export type BusinessType = {
    __kind__: "hotel";
    hotel: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "temple";
    temple: null;
} | {
    __kind__: "restaurant";
    restaurant: null;
} | {
    __kind__: "corporate";
    corporate: null;
};
export type Time = bigint;
export interface backendInterface {
    getAllEnquiries(): Promise<Array<LeadRequest>>;
    submitEnquiry(lead: LeadRequest): Promise<void>;
}
import type { BusinessType as _BusinessType, LeadRequest as _LeadRequest, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllEnquiries(): Promise<Array<LeadRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEnquiry(arg0: LeadRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(to_candid_LeadRequest_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(to_candid_LeadRequest_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BusinessType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LeadRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadRequest): LeadRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    businessName: string;
    businessType: _BusinessType;
    email: [] | [string];
    message: string;
    timestamp: _Time;
    phone: [] | [string];
    budgetRange: string;
}): {
    city: string;
    businessName: string;
    businessType: BusinessType;
    email?: string;
    message: string;
    timestamp: Time;
    phone?: string;
    budgetRange: string;
} {
    return {
        city: value.city,
        businessName: value.businessName,
        businessType: from_candid_BusinessType_n4(_uploadFile, _downloadFile, value.businessType),
        email: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.email)),
        message: value.message,
        timestamp: value.timestamp,
        phone: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.phone)),
        budgetRange: value.budgetRange
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: null;
} | {
    other: string;
} | {
    temple: null;
} | {
    restaurant: null;
} | {
    corporate: null;
}): {
    __kind__: "hotel";
    hotel: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "temple";
    temple: null;
} | {
    __kind__: "restaurant";
    restaurant: null;
} | {
    __kind__: "corporate";
    corporate: null;
} {
    return "hotel" in value ? {
        __kind__: "hotel",
        hotel: value.hotel
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "temple" in value ? {
        __kind__: "temple",
        temple: value.temple
    } : "restaurant" in value ? {
        __kind__: "restaurant",
        restaurant: value.restaurant
    } : "corporate" in value ? {
        __kind__: "corporate",
        corporate: value.corporate
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadRequest>): Array<LeadRequest> {
    return value.map((x)=>from_candid_LeadRequest_n2(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_LeadRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadRequest): _LeadRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    businessName: string;
    businessType: BusinessType;
    email?: string;
    message: string;
    timestamp: Time;
    phone?: string;
    budgetRange: string;
}): {
    city: string;
    businessName: string;
    businessType: _BusinessType;
    email: [] | [string];
    message: string;
    timestamp: _Time;
    phone: [] | [string];
    budgetRange: string;
} {
    return {
        city: value.city,
        businessName: value.businessName,
        businessType: to_candid_BusinessType_n9(_uploadFile, _downloadFile, value.businessType),
        email: value.email ? candid_some(value.email) : candid_none(),
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        budgetRange: value.budgetRange
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "hotel";
    hotel: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "temple";
    temple: null;
} | {
    __kind__: "restaurant";
    restaurant: null;
} | {
    __kind__: "corporate";
    corporate: null;
}): {
    hotel: null;
} | {
    other: string;
} | {
    temple: null;
} | {
    restaurant: null;
} | {
    corporate: null;
} {
    return value.__kind__ === "hotel" ? {
        hotel: value.hotel
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "temple" ? {
        temple: value.temple
    } : value.__kind__ === "restaurant" ? {
        restaurant: value.restaurant
    } : value.__kind__ === "corporate" ? {
        corporate: value.corporate
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
